apiVersion: batch/v1
kind: CronJob
metadata:
  name: qa-automation-cron
  namespace: default
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 120
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: qa-automation
              image: sdaia-test:latest
              imagePullPolicy: Never
              workingDir: /app
              command: ["/bin/sh", "-c"]
              args: ["behave -f pretty --no-capture -o ./reports/results.txt"]
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "256Mi"
                  cpu: "250m"
              volumeMounts:
                - name: reports
                  mountPath: /reports
          volumes:
            - name: reports
              emptyDir: {}
